language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    sources:
    - nodejs
    - npm

env:
  global:
    secure: DUIx/SHA257at6LNHojTY3361yAhtBjra7fycZUVkAMuY4I9KiQbCY3Lu9NYvfrkrdCODxYB5d+ooeG+zUvM8/yvoWN7lYkpjNrHGfJ3+TTC0JF48xKiLp8TUXwBKM4VwnVtFUezhqgNJZ6C4SZbI9FoG3ACxNoXqszQvSFcRyGN2KprFTTrwA0M9geA8sZV68BXWvJfdQCBNyKyxcYJcIDNFJKRRXuECTEXny69XTaBycds8gi7/X6NNuE8EIWmIo3VcmSuBiJLpiCes+3JPsY/+ZGJxT4QupICefMKFHcvP8VldP6rLnub0WUp+vdsHFvqNaGxcbQMUSeXnKGTehdv0dMW4vHlNfVGWtOFnBbT/ILAKHDk1RmZO9ZmoY5UPp79MGYUU1G6bk1nt4g1ueivGMwnUY4CwSN5JFDcxc5YkpMO+9uclEMpKyCs6IPtlM56ddjcDzJPjH5MkrujaA/8twL5bfPyrQ8FynSeMD1l08pRWjPRszzjnagVMuIcapev++4Pq/5qRDWZoqwUcMD4F/RIeARMfa/K0KUbp2BbqUS9xrNFIAzL/K8yVhRJ/zjGCsEkUgQfJF1rYBcW1VZVbopMLzoHKsjCVclrxqdqNyApnl5L2NEFo4yCeu9Cm0YrvOIJVFJBDT9AwM77nRO7354azj2VdMpZYe3BzEg=

script:
  # Википедия блокирует подсеть Travis'а... (так как когда-то я в нём запускал автоматическую ёфикацию в знак протеста против их отказа выдавать мне флаг автопатрулируемого) и подсеть Heroku, поэтому сделать онлайн сборку скрипта не получится
  #  - "./web-frontend/update-script-at-wikipedia.sh"
  - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then ./cpp-frequencies/update_frequencies_on_github.sh; fi

before_deploy:
  - cd ./web-backend

deploy:
  provider: heroku
  app: yofication
  api_key:
    secure: "bCyHgxpDb/FkT94EY7l8CmREozhQolBoOd90/Pf4ITi8gGKT1P0vaoPc0Wm0L0J57uCQW9b/gjtrQ703Qp/udeVb+4UeC7htqL2K5gfYtoXrnOrNGzHT/WS7m8xC6bDQ5+wxVfuwwkESnd1wNjfxlPoW1dpFI9B0BLKsX48Z3CuD574fweRV1dt1FHAArz7SqQ3SjANk6mTBpWCZJNrqgsHuRG4LrOgVoovKl1U+oBeKBKIeAcibUAksqvyy/qV2pQGfiNOfvByITO9DOE3eR0FnrcnGAci+LEIHJFG0Rom4dG2JGo8oow9w3tB+SMb6iMhceUn9tk4C+6wYE+OYLI5jYV8j0M2Z2y9SthawZ5NdJZ2lL7K3bBiWVTmJVkM1S2zKIbcLUWUNRZTc6+ELSCsKsfKXcYA50WdLtBenaUJxIy+BDNrDhcZHOpeLiehtUxl568YjHGL8DuyR/Wnknl7bpKA78Qe2X5Jx0G1HVY1esRP7CbaiZ5A9tEi0cV7nsi9QXqvQj087vZ15QfJJ4xurej2p8PlpZVI++OiGgYgjPETYIVLUNDJr5mmpNV6qgjtb2AgFUL8gv5YtiZfIJvnX1ToKMjksZf4uWfKrcBD0aNkYy9SVS8MW7/xvv0ggFCHYhUBBNKAWatpKv+buvh9FSzf0Iisky5Zt2tMYcjA="
