language: cpp
sudo: required

arch:
  packages:
    - tree
    - cmake
  script:
    - tree

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
