language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    sources:
    - nodejs
    - npm

env:
  global:
    secure: DUIx/SHA257at6LNHojTY3361yAhtBjra7fycZUVkAMuY4I9KiQbCY3Lu9NYvfrkrdCODxYB5d+ooeG+zUvM8/yvoWN7lYkpjNrHGfJ3+TTC0JF48xKiLp8TUXwBKM4VwnVtFUezhqgNJZ6C4SZbI9FoG3ACxNoXqszQvSFcRyGN2KprFTTrwA0M9geA8sZV68BXWvJfdQCBNyKyxcYJcIDNFJKRRXuECTEXny69XTaBycds8gi7/X6NNuE8EIWmIo3VcmSuBiJLpiCes+3JPsY/+ZGJxT4QupICefMKFHcvP8VldP6rLnub0WUp+vdsHFvqNaGxcbQMUSeXnKGTehdv0dMW4vHlNfVGWtOFnBbT/ILAKHDk1RmZO9ZmoY5UPp79MGYUU1G6bk1nt4g1ueivGMwnUY4CwSN5JFDcxc5YkpMO+9uclEMpKyCs6IPtlM56ddjcDzJPjH5MkrujaA/8twL5bfPyrQ8FynSeMD1l08pRWjPRszzjnagVMuIcapev++4Pq/5qRDWZoqwUcMD4F/RIeARMfa/K0KUbp2BbqUS9xrNFIAzL/K8yVhRJ/zjGCsEkUgQfJF1rYBcW1VZVbopMLzoHKsjCVclrxqdqNyApnl5L2NEFo4yCeu9Cm0YrvOIJVFJBDT9AwM77nRO7354azj2VdMpZYe3BzEg=

script:
  # Википедия блокирует подсеть Travis'а... (так как когда-то я в нём запускал автоматическую ёфикацию в знак протеста против их отказа выдавать мне флаг автопатрулируемого) и подсеть Heroku, поэтому сделать онлайн сборку скрипта не получится
  #  - "./web-frontend/update-script-at-wikipedia.sh"
  - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then ./cpp-frequencies/update_frequencies_on_github.sh; fi

before_deploy:
  - cd ./web-backend

deploy:
  provider: heroku
  app: yofication
  api_key:
    secure: "X2YX4MPx0rNDd3j3rL1PiQA0zLnF2QUiw+YiEuSJR7LV1c7vo2lk4ckMSxLdmsY4SpfrEhL2MbgLSJSsJtvZvcPrQdylSi7xVqMuBHayzqla68b5WW9pWg/52lw9/6vVqBa4TNgXTop0gguJ/v5O632cLz/qoqMeQ8/D7WLRNU8DEwhqhkGG/joUe8QyMWSe8U/ghz7dhgCxMGKNOQcjv5HA2WfNZUa5A6BgmPMUWbJBb+3haB1IKIPXem0T1hNYovXNeWt3oOLqnfVgM0iOMMtv6oFA39AyTLZKjSB5HhfMCnX6VItSaexPn2neTW8m+CWzZVFnZdvkUbz/ZXbdEermfRMea+A7T78GACgYUXhXAiYoDkSFACRHOJjKBqWzG1cF8wZIVaAUSnBhnr3mnMXEGKRDK9+1DuA0RE/gZhz1oNzKF8LSzeYidIU7ZWVjuJ7pe14RS6se881x27XLJRXUBRWfwWFvQnm9TWHZCwmUuiPu2x38Wmar892TjpibMtXOSHTdZ6I25d7vMT3HBpV+AGDs4cFAepCpIxqK4UXRjE6K1HkMSGwC5rK7bls7HCOJo3Zxd10p0AMqqHJK+ZtYRkhypMRNEkXlB1Gj5TIHfld+n6PfuAUAA2ypY9OuFHUlwxo59hnLBFndJglNMDkPKRVBHah2SBVIshH5zeQ="
