language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    sources:
    - nodejs
    - npm

env:
  global:
    secure: DUIx/SHA257at6LNHojTY3361yAhtBjra7fycZUVkAMuY4I9KiQbCY3Lu9NYvfrkrdCODxYB5d+ooeG+zUvM8/yvoWN7lYkpjNrHGfJ3+TTC0JF48xKiLp8TUXwBKM4VwnVtFUezhqgNJZ6C4SZbI9FoG3ACxNoXqszQvSFcRyGN2KprFTTrwA0M9geA8sZV68BXWvJfdQCBNyKyxcYJcIDNFJKRRXuECTEXny69XTaBycds8gi7/X6NNuE8EIWmIo3VcmSuBiJLpiCes+3JPsY/+ZGJxT4QupICefMKFHcvP8VldP6rLnub0WUp+vdsHFvqNaGxcbQMUSeXnKGTehdv0dMW4vHlNfVGWtOFnBbT/ILAKHDk1RmZO9ZmoY5UPp79MGYUU1G6bk1nt4g1ueivGMwnUY4CwSN5JFDcxc5YkpMO+9uclEMpKyCs6IPtlM56ddjcDzJPjH5MkrujaA/8twL5bfPyrQ8FynSeMD1l08pRWjPRszzjnagVMuIcapev++4Pq/5qRDWZoqwUcMD4F/RIeARMfa/K0KUbp2BbqUS9xrNFIAzL/K8yVhRJ/zjGCsEkUgQfJF1rYBcW1VZVbopMLzoHKsjCVclrxqdqNyApnl5L2NEFo4yCeu9Cm0YrvOIJVFJBDT9AwM77nRO7354azj2VdMpZYe3BzEg=

script:
  # Википедия блокирует подсеть Travis'а... (так как когда-то я в нём запускал автоматическую ёфикацию в знак протеста против их отказа выдавать мне флаг автопатрулируемого) и подсеть Heroku, поэтому сделать онлайн сборку скрипта не получится
  #  - "./web-frontend/update-script-at-wikipedia.sh"
  - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then ./cpp-frequencies/update_frequencies_on_github.sh; fi

before_deploy:
  - cd ./web-backend

deploy:
  provider: heroku
  app: yofication
  api_key:
    secure: WXgEE0kw+8BRN0XMIVuEfP4OJqovbR2AQ9JXuDXZtVUrj755NAjAGmrAQTTCyTb+1vbl/8sD5jc2LWa1ied6FqnQEmHAuE3RSN5DDyEMbvODh0izuLW3MM1qkitPTSvMn7NRHNVjaaW7+eLlLZjiUFn0VZOmOryda4YxEdbwiGuFSI2rxhh/MeLoGXzXFq+vkYQviK7Pd15D9ByRZdArKD2+bl/+taj7+3AKzcLNCUv/kXWQASUc5qIR9xptIfz+rf/nLh2k0+v95fwvUVatHgBFqWkmoOJSOKGTG71f5XbU6PPHJCgwJk1nWlNyHV43L1KYT/YMSfXqn1N/JZEITqd+d/IoUH0IIF213lCF331JLLNK8K6fu3QvEs3sE9qgKDkkiTiSRJNtv2fSmf/8DJV8RlV3p2++3WuDmVjrcu2+B2y/Oclv020qTOxRIi3Hyjv7Zi9L48xdK4bdUSTgmmrDxL8DuqDktiffckbfXQF1HHSTW+8f5WlkgW27xlV/dmRWrDSqE76AAviGabHx8M5c+xyvrD2Fz/9qaxSkj2WWtIC8I7+FeSS6xQd3qSJuKqY36ECrzP0eTEdUK24uBj6ZUXI2JXRonKyh6NrWNCggIW52GJO1AB7JxpiVRNVOP+V+R4cjyD3OB5ZXEWBspWHePd+suvAVqTvbUtBPRpc=
