language: cpp
sudo: required

arch:
  packages:
    - tree
    - cmake
  script:
    - pwd
    - ls
    - tree

    - mkdir build
    - cd build

    - pwd
    - ls
    - tree

    - cmake ..

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
