language: cpp
sudo: required

arch:
  packages:
    - tree
    - cmake
    - nodejs
    - npm
    - python
    - python-pip
    - yaourt
  script:
    - "./build_script.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
