language: cpp
sudo: required

arch:
  packages:
    - tree
    - cmake
  script:
    - pwd
    - mkdir build
    - cd build
    - ls ..
    - pwd
    - cmake ..

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
