version: 2

jobs:
  test:
    working_directory: ~/project/backend
    docker:
      - image: circleci/rust
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Test
          command: cargo test
  frequencies:
    working_directory: ~/project/frequencies
    docker:
      - image: circleci/rust
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Generate frequencies and all-pages
          command: |
            mkdir results
            cargo run --release
          no_output_timeout: 60m
      - run:
          name: Update frequencies on github
          command: ./update_frequencies_on_github.sh
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git subtree push --prefix backend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy:
          requires:
            - test
  frequencies:
    triggers:
      - schedule:
          cron: "0 0 7 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - frequencies
