version: 2

jobs:
  test:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test
  frequencies:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Generate frequencies and all-pages
          command: |
            mkdir results
            cargo run --bin frequencies --release
          no_output_timeout: 70m
      - run:
          name: Update frequencies on github
          command: ./update_frequencies_on_github.sh
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy:
          requires:
            - test
  frequencies_cron:
    jobs:
      - frequencies
    triggers:
      - schedule:
          cron: "0 0 7 * *"
          filters:
            branches:
              only:
                - master
  frequencies:
#    чтобы инициировать подсчёт частот нужно добавить тег frequencies_trigger к коммиту:
#        git tag frequencies_trigger && git push origin frequencies_trigger
#    затем его можно удалить
#        git tag -d frequencies_trigger && git push origin :frequencies_trigger
    jobs:
      - frequencies:
          filters:
            tags:
              only: frequencies_trigger
            branches:
              ignore: /.*/
