[package]
name = "frequencies"
version = "0.1.0"
authors = ["Dmitry Murzin <diraria@yandex.ru>"]
edition = "2018"

[dependencies]
bzip2 = "0.3.3"
reqwest = "0.9.11"
itertools = "0.8.0"
backend-common = { path = "../backend-common" }
